// import google fonts
import { Poppins } from 'next/font/google'
import './globals.css'

import Header from './components/Header'

const poppins = Poppins({
  weight: ['400', '800'],
  subsets: ['latin']
})

export const metadata = {
  title: 'Next Crash Course App',
  description: 'Generated by create next app',
  // SEO - Keywords
  keywords:
    'web development, web design, javascript, react,node,nextjs,html,css'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={poppins.className}>
        <Header />
        <main className='container'>{children}</main>
      </body>
    </html>
  )
}
